---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      serviceAccountName: nginx
      securityContext:
        runAsNonRoot: false
      containers:
      - image: nginx@sha256:943c25b4b66b332184d5ba6bb18234273551593016c0e0ae906bab111548239f
        name: nginx
        ports:
          - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "150M"
          limits:
            cpu: "100m"
            memory: "150M"
            
