apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: aspnetapp
  name: aspnetapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aspnetapp
  template:
    metadata:
      labels:
        app: aspnetapp
    spec:
      containers:
      - image: aspnetapp
        name: app
        resources:
          requests:
            cpu: "100m"
            memory: "50Mi"
          limits:
            memory: "50Mi"
