apiVersion: batch/v1
kind: Job
metadata:
  name: nginx-data-init
spec:
  template:
    spec:
      serviceAccountName: nginx
      restartPolicy: OnFailure
      containers:
      - name: init
        image: nginx
        command:
        - "/bin/bash"
        args:
        - "-c"
        - "echo '<h1>Welcome from nginx with persistent volume</h1>' > /data/index.html; echo 'DONE'"
        volumeMounts:
        - name: www
          mountPath: /data
      volumes:
      - name: www
        persistentVolumeClaim:
          claimName: nginx-data